# frozen_string_literal: true

module Spior
  module Tor
    # Generate a config file (torrc) for Spior
    class Config
      # ==== Attributes
      #
      # * +filename+ - A reference to a tempfile like filename=Tempfile.new('foo')
      #
      def initialize(filename)
        @filename = filename
        @content = <<~TORRC
        # Generated by Spior, don't edit.
        RunAsDaemon 1
        ClientOnly 1
        SocksPort 9055
        DNSPort 127.0.0.1:9061
        VirtualAddrNetworkIpv4 10.192.0.0/10
        TransPort 9040 IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort
        TORRC
      end

      # Generate a `torrc` compatible file for Spior
      # Use value from Spior::CONFIG
      def generate
        Msg.p "Generating Tor config to #{@filename.path}..."
        File.write @filename.path, "#{@content}\n"
      end
    end
  end
end
