# frozen_string_literal: true

module Spior
  module Tor
    # Generate a config file for Spior
    class Config
      def initialize(filename)
        @filename = filename
        @content = <<~TORRC
        # Generated by Spior, don't edit.
        RunAsDaemon 1
        ClientOnly 1
        SocksPort 127.0.0.1:9055
        AutomapHostsOnResolve 1
        DNSPort #{CONFIG.dns_listen_address}:#{CONFIG.dns_port}
        VirtualAddrNetworkIpv4 #{CONFIG.virt_addr}
        TransPort #{CONFIG.trans_port} IsolateClientAddr IsolateClientProtocol IsolateDestAddr IsolateDestPort
        TORRC
      end

      def generate
        Msg.p "Generating Tor config to #{@filename.path}..."
        File.write @filename.path, "#{@content}\n"
      end
    end
  end
end
